/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.0-51-g2d9b1ad

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: BTT-Intellistep-CANopen.xdd
        File Version: 101

        Created:      26.11.2014 16:35:00
        Created By:   IhorNehrutsa
        Modified:     18.08.2021 15:06:26
        Modified By:  IhorNehrutsa

    Device Info:
        Vendor Name:  Intellistep
        Vendor ID:    0x00000331
        Product Name: BTT-Intellistep-CANopen
        Product ID:   0x00008200

        Description:  EDS BTT-Intellistep-CANopen Slave
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_HB_CONS 1
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SDO_SRV 0
#define OD_CNT_SDO_CLI 0
#define OD_CNT_TIME 0
#define OD_CNT_SYNC 1
#define OD_CNT_RPDO 1
#define OD_CNT_TPDO 1
#define OD_CNT_GFC 0
#define OD_CNT_SRDO 0


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 4
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 5
#define OD_CNT_ARR_2005 2
#define OD_CNT_ARR_2010 2
#define OD_CNT_ARR_2152 4
#define OD_CNT_ARR_2153 4
#define OD_CNT_ARR_60FE 2


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint8_t x1003_pre_definedErrorField_sub0;
    uint32_t x1003_pre_definedErrorField[OD_CNT_ARR_1003];
    uint32_t x1005_COB_ID_SYNC;
    uint32_t x1006_cyclePeriod;
    uint32_t x1007_syncWindowsLength;
    char x1008_deviceName[24];
    char x1009_hardwareVersion[6];
    char x100A_softwareVersion[6];
    uint16_t x100C_guardTime;
    uint8_t x100D_lifeTimeFactor;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_CNT_ARR_1011];
    uint32_t x1014_COB_ID_EmergencyMessage;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identityObject;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t PDOMapping_1_appObject;
        uint32_t PDOMapping_2_appObject;
        uint32_t PDOMapping_3_appObject;
        uint32_t PDOMapping_4_appObject;
        uint32_t PDOMapping_5_appObject;
        uint32_t PDOMapping_6_appObject;
        uint32_t PDOMapping_7_appObject;
        uint32_t PDOMapping_8_appObject;
    } x1600_RPDO_1_mappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t PDOMapping_1_appObject;
        uint32_t PDOMapping_2_appObject;
        uint32_t PDOMapping_3_appObject;
        uint32_t PDOMapping_4_appObject;
        uint32_t PDOMapping_5_appObject;
        uint32_t PDOMapping_6_appObject;
        uint32_t PDOMapping_7_appObject;
        uint32_t PDOMapping_8_appObject;
    } x1602_RPDO_3_mappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t PDOMapping_1_appObject;
        uint32_t PDOMapping_2_appObject;
        uint32_t PDOMapping_3_appObject;
        uint32_t PDOMapping_4_appObject;
        uint32_t PDOMapping_5_appObject;
        uint32_t PDOMapping_6_appObject;
        uint32_t PDOMapping_7_appObject;
        uint32_t PDOMapping_8_appObject;
    } x1603_RPDO_4_mappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t PDOMapping_1_appObject;
        uint32_t PDOMapping_3_appObject;
        uint32_t PDOMapping_4_appObject;
        uint32_t PDOMapping_5_appObject;
        uint32_t PDOMapping_6_appObject;
        uint32_t PDOMapping_7_appObject;
        uint32_t PDOMapping_8_appObject;
    } x1604_RPDO_5_mappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t PDOMapping_1_appObject;
        uint32_t PDOMapping_3_appObject;
        uint32_t PDOMapping_4_appObject;
        uint32_t PDOMapping_5_appObject;
        uint32_t PDOMapping_6_appObject;
        uint32_t PDOMapping_7_appObject;
        uint32_t PDOMapping_8_appObject;
    } x1605_RPDO_6_mappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t PDOMapping_1_appObject;
        uint32_t PDOMapping_2_appObject;
        uint32_t PDOMapping_3_appObject;
        uint32_t PDOMapping_4_appObject;
        uint32_t PDOMapping_5_appObject;
        uint32_t PDOMapping_6_appObject;
        uint32_t PDOMapping_7_appObject;
        uint32_t PDOMapping_8_appObject;
    } x1A00_TPDO_1_mappingParameter;
    struct {
        uint8_t numberOfMappedAppObjects;
        uint32_t PDOMapping_1_appObject;
        uint32_t PDOMapping_2_appObject;
        uint32_t PDOMapping_3_appObject;
        uint32_t PDOMapping_4_appObject;
        uint32_t PDOMapping_5_appObject;
        uint32_t PDOMapping_6_appObject;
        uint32_t PDOMapping_7_appObject;
        uint32_t PDOMapping_8_appObject;
    } x1A02_TPDO_3_mappingParameter;
    struct {
        uint8_t numberOfMappedAppObjects;
        uint32_t PDOMapping_1_appObject;
        uint32_t PDOMapping_2_appObject;
        uint32_t PDOMapping_3_appObject;
        uint32_t PDOMapping_4_appObject;
        uint32_t PDOMapping_5_appObject;
        uint32_t PDOMapping_6_appObject;
        uint32_t PDOMapping_7_appObject;
        uint32_t PDOMapping_8_appObject;
    } x1A03_TPDO_4_mappingParameter;
    struct {
        uint8_t numberOfMappedAppObjects;
        uint32_t PDOMapping_1_appObject;
        uint32_t PDOMapping_3_appObject;
        uint32_t PDOMapping_4_appObject;
        uint32_t PDOMapping_5_appObject;
        uint32_t PDOMapping_6_appObject;
        uint32_t PDOMapping_7_appObject;
        uint32_t PDOMapping_8_appObject;
    } x1A04_TPDO_5_mappingParameter;
    struct {
        uint8_t numberOfMappedAppObjects;
        uint32_t PDOMapping_1_appObject;
        uint32_t PDOMapping_3_appObject;
        uint32_t PDOMapping_4_appObject;
        uint32_t PDOMapping_5_appObject;
        uint32_t PDOMapping_6_appObject;
        uint32_t PDOMapping_7_appObject;
        uint32_t PDOMapping_8_appObject;
    } x1A05_TPDO_6_mappingParameter;
    uint16_t x2000_currentPeak;
    uint16_t x2001_motorResolution;
    uint16_t x2002_standbyTime;
    uint16_t x2003_standbyCurrentPercentage;
    uint8_t x2005_outputs_function_sub0;
    uint16_t x2005_outputs_function[OD_CNT_ARR_2005];
    uint16_t x2006_enableValidLevel;
    uint16_t x2007_disableMode;
    uint16_t x2008_output1_set;
    uint16_t x2009_filterEnable;
    uint8_t x2010_filterTime_sub0;
    uint16_t x2010_filterTime[OD_CNT_ARR_2010];
    uint16_t x2012_softStartTime;
    uint16_t x2013_autotuneEnable;
    uint16_t x2015_currentLoopKp;
    uint16_t x2016_currentLoopKi;
    uint16_t x2017_currentLoopKc;
    uint16_t x2020_motorResistance;
    uint16_t x2021_motorInductance;
    uint16_t x2022_stepTestCurrent;
    uint16_t x2023_stepTestStartStop;
    uint16_t x2024_closeLoopSwitch;
    uint16_t x2026_openCurrentPercentage;
    uint16_t x2027_closeCurrentPercentage;
    uint16_t x2028_antiDisturbanceTime;
    uint16_t x2030_positionErrorAlarmRange;
    uint16_t x2031_positionErrorAlarmEnable;
    uint16_t x2032_dataAcquisitionStartStop;
    uint16_t x2033_dataSampleTime;
    uint16_t x2034_sampleTypeOfChannel_1;
    uint16_t x2035_positionLoopKp;
    uint16_t x2036_positionLoopKi;
    uint16_t x2037_positionLoopKd;
    uint16_t x2038_positionLoopKvff;
    int16_t x2039_sumOfPluseInputH;
    int16_t x2040_sumOfPluseInputL;
    int16_t x2041_sumOfPluseFeedbackH;
    int16_t x2042_sumOfPluseFeedbackL;
    int16_t x2043_speedReference;
    int16_t x2044_speedFeedback;
    uint16_t x2046_advanceAngle;
    uint16_t x2047_actualSetCurrent;
    uint16_t x2048_busVoltage;
    uint16_t x2049_pulseMode;
    uint16_t x2050_pulseEdgeLevel;
    uint16_t x2051_motorRunningDirection;
    uint16_t x2052_sampleDataType;
    uint16_t x2053_outputModeOfTargetReached;
    uint16_t x2054_antiVibrationCoefficient;
    uint16_t x2056_faultDetectSet;
    uint16_t x2057_clearFaultEnable;
    uint16_t x2058_softStartTime;
    uint16_t x2059_reserve;
    uint16_t x2060_amplitudeOfFirstAntiVibration;
    uint16_t x2061_phaseAOfFirstAntiVibration;
    uint16_t x2062_phaseBOfFirstAntiVibration;
    uint16_t x2063_amplitudeOfSecondAntiVibration;
    uint16_t x2064_phaseAOfSecondAntiVibration;
    uint16_t x2065_phaseBOfSecondAntiVibration;
    uint16_t x2066_amplitudeOfThirdAntiVibration;
    uint16_t x2067_phaseAOfThirdAntiVibration;
    uint16_t x2068_phaseBOfThirdAntiVibration;
    uint16_t x2069_amplitudeOfFourthAntiVibration;
    uint16_t x2070_phaseAOfFourthAntiVibration;
    uint16_t x2071_phaseBOfFourthAntiVibration;
    uint16_t x2072_phaseOfZShaftAntiVibration;
    uint16_t x2073_motorReturnPowerOn;
    uint16_t x2074_torqueFeedforward;
    uint16_t x2075_gravity_compensation;
    uint16_t x2076_pulseTargetReached;
    uint16_t x2093_clearFaultRecord;
    uint16_t x2094_sampleTypeOfChannel_2;
    uint16_t x2095_sampleTypeOfChannel_3;
    uint16_t x2096_sampleTypeOfChannel_4;
    uint16_t x2097_sampleTypeOfChannel_5;
    uint16_t x2098_sampleTypeOfChannel_6;
    uint16_t x2099_channelSelection;
    uint16_t x2150_node_ID;
    uint16_t x2151_node_BaudRate;
    uint8_t x2152_inputIoFunctionSet_sub0;
    uint16_t x2152_inputIoFunctionSet[OD_CNT_ARR_2152];
    uint8_t x2153_inputIoFilterTime_sub0;
    uint16_t x2153_inputIoFilterTime[OD_CNT_ARR_2153];
    uint16_t x2154_inputIoPolarity;
    uint16_t x2155_inputIoLevel;
    uint16_t x2162_trans_loworhigh;
    struct {
        uint8_t numberOfEntries;
        uint16_t error_2;
    } x3FFE_errorTable;
    uint16_t x4000_motor_code;
    uint16_t x4001_stall_detect_enable;
    uint16_t x4002_stall_proess_set;
    uint16_t x5000_motionFlag;
    uint16_t x5FFF_simulateDriveFaultState;
    uint16_t x6040_controlword;
    uint16_t x6041_statusword;
    int8_t x6060_modesOfOperation;
    int8_t x6061_modesOfOperationDisplay;
    int32_t x6062_commanded_position;
    int32_t x6064_positionActualValue;
    int32_t x606B_velocityDemandValue;
    int32_t x606C_velocityActualValue;
    int32_t x607A_targetPosition;
    int32_t x607C_homeOffset;
    uint32_t x6081_profileVelocity;
    uint32_t x6082_end_velocity;
    uint32_t x6083_profileAcceleration;
    uint32_t x6084_profileDeceleration;
    uint32_t x6085_quick_stop_deceleration;
    int8_t x6098_hmHomingMethode;
    uint32_t x609A_hm_homing_acceleration;
    uint8_t x60FE_digital_output_sub0;
    int32_t x60FF_targetVelocity;
} OD_RAM_t;

typedef struct {
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
        uint32_t mappedObject_2;
        uint32_t mappedObject_3;
        uint32_t mappedObject_4;
        uint32_t mappedObject_5;
        uint32_t mappedObject_6;
        uint32_t mappedObject_7;
        uint32_t mappedObject_8;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
        uint32_t mappedObject_2;
        uint32_t mappedObject_3;
        uint32_t mappedObject_4;
        uint32_t mappedObject_5;
        uint32_t mappedObject_6;
        uint32_t mappedObject_7;
        uint32_t mappedObject_8;
    } x1A01_TPDOMappingParameter;
} OD_ROM_t;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_ROM
#define OD_ATTR_ROM
#endif
extern OD_ATTR_ROM OD_ROM_t OD_ROM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1006 &OD->list[4]
#define OD_ENTRY_H1007 &OD->list[5]
#define OD_ENTRY_H1008 &OD->list[6]
#define OD_ENTRY_H1009 &OD->list[7]
#define OD_ENTRY_H100A &OD->list[8]
#define OD_ENTRY_H100C &OD->list[9]
#define OD_ENTRY_H100D &OD->list[10]
#define OD_ENTRY_H1010 &OD->list[11]
#define OD_ENTRY_H1011 &OD->list[12]
#define OD_ENTRY_H1014 &OD->list[13]
#define OD_ENTRY_H1016 &OD->list[14]
#define OD_ENTRY_H1017 &OD->list[15]
#define OD_ENTRY_H1018 &OD->list[16]
#define OD_ENTRY_H1401 &OD->list[17]
#define OD_ENTRY_H1600 &OD->list[18]
#define OD_ENTRY_H1601 &OD->list[19]
#define OD_ENTRY_H1602 &OD->list[20]
#define OD_ENTRY_H1603 &OD->list[21]
#define OD_ENTRY_H1604 &OD->list[22]
#define OD_ENTRY_H1605 &OD->list[23]
#define OD_ENTRY_H1801 &OD->list[24]
#define OD_ENTRY_H1A00 &OD->list[25]
#define OD_ENTRY_H1A01 &OD->list[26]
#define OD_ENTRY_H1A02 &OD->list[27]
#define OD_ENTRY_H1A03 &OD->list[28]
#define OD_ENTRY_H1A04 &OD->list[29]
#define OD_ENTRY_H1A05 &OD->list[30]
#define OD_ENTRY_H2000 &OD->list[31]
#define OD_ENTRY_H2001 &OD->list[32]
#define OD_ENTRY_H2002 &OD->list[33]
#define OD_ENTRY_H2003 &OD->list[34]
#define OD_ENTRY_H2005 &OD->list[35]
#define OD_ENTRY_H2006 &OD->list[36]
#define OD_ENTRY_H2007 &OD->list[37]
#define OD_ENTRY_H2008 &OD->list[38]
#define OD_ENTRY_H2009 &OD->list[39]
#define OD_ENTRY_H2010 &OD->list[40]
#define OD_ENTRY_H2012 &OD->list[41]
#define OD_ENTRY_H2013 &OD->list[42]
#define OD_ENTRY_H2015 &OD->list[43]
#define OD_ENTRY_H2016 &OD->list[44]
#define OD_ENTRY_H2017 &OD->list[45]
#define OD_ENTRY_H2020 &OD->list[46]
#define OD_ENTRY_H2021 &OD->list[47]
#define OD_ENTRY_H2022 &OD->list[48]
#define OD_ENTRY_H2023 &OD->list[49]
#define OD_ENTRY_H2024 &OD->list[50]
#define OD_ENTRY_H2026 &OD->list[51]
#define OD_ENTRY_H2027 &OD->list[52]
#define OD_ENTRY_H2028 &OD->list[53]
#define OD_ENTRY_H2030 &OD->list[54]
#define OD_ENTRY_H2031 &OD->list[55]
#define OD_ENTRY_H2032 &OD->list[56]
#define OD_ENTRY_H2033 &OD->list[57]
#define OD_ENTRY_H2034 &OD->list[58]
#define OD_ENTRY_H2035 &OD->list[59]
#define OD_ENTRY_H2036 &OD->list[60]
#define OD_ENTRY_H2037 &OD->list[61]
#define OD_ENTRY_H2038 &OD->list[62]
#define OD_ENTRY_H2039 &OD->list[63]
#define OD_ENTRY_H2040 &OD->list[64]
#define OD_ENTRY_H2041 &OD->list[65]
#define OD_ENTRY_H2042 &OD->list[66]
#define OD_ENTRY_H2043 &OD->list[67]
#define OD_ENTRY_H2044 &OD->list[68]
#define OD_ENTRY_H2046 &OD->list[69]
#define OD_ENTRY_H2047 &OD->list[70]
#define OD_ENTRY_H2048 &OD->list[71]
#define OD_ENTRY_H2049 &OD->list[72]
#define OD_ENTRY_H2050 &OD->list[73]
#define OD_ENTRY_H2051 &OD->list[74]
#define OD_ENTRY_H2052 &OD->list[75]
#define OD_ENTRY_H2053 &OD->list[76]
#define OD_ENTRY_H2054 &OD->list[77]
#define OD_ENTRY_H2056 &OD->list[78]
#define OD_ENTRY_H2057 &OD->list[79]
#define OD_ENTRY_H2058 &OD->list[80]
#define OD_ENTRY_H2059 &OD->list[81]
#define OD_ENTRY_H2060 &OD->list[82]
#define OD_ENTRY_H2061 &OD->list[83]
#define OD_ENTRY_H2062 &OD->list[84]
#define OD_ENTRY_H2063 &OD->list[85]
#define OD_ENTRY_H2064 &OD->list[86]
#define OD_ENTRY_H2065 &OD->list[87]
#define OD_ENTRY_H2066 &OD->list[88]
#define OD_ENTRY_H2067 &OD->list[89]
#define OD_ENTRY_H2068 &OD->list[90]
#define OD_ENTRY_H2069 &OD->list[91]
#define OD_ENTRY_H2070 &OD->list[92]
#define OD_ENTRY_H2071 &OD->list[93]
#define OD_ENTRY_H2072 &OD->list[94]
#define OD_ENTRY_H2073 &OD->list[95]
#define OD_ENTRY_H2074 &OD->list[96]
#define OD_ENTRY_H2075 &OD->list[97]
#define OD_ENTRY_H2076 &OD->list[98]
#define OD_ENTRY_H2093 &OD->list[99]
#define OD_ENTRY_H2094 &OD->list[100]
#define OD_ENTRY_H2095 &OD->list[101]
#define OD_ENTRY_H2096 &OD->list[102]
#define OD_ENTRY_H2097 &OD->list[103]
#define OD_ENTRY_H2098 &OD->list[104]
#define OD_ENTRY_H2099 &OD->list[105]
#define OD_ENTRY_H2150 &OD->list[106]
#define OD_ENTRY_H2151 &OD->list[107]
#define OD_ENTRY_H2152 &OD->list[108]
#define OD_ENTRY_H2153 &OD->list[109]
#define OD_ENTRY_H2154 &OD->list[110]
#define OD_ENTRY_H2155 &OD->list[111]
#define OD_ENTRY_H2162 &OD->list[112]
#define OD_ENTRY_H3FFE &OD->list[113]
#define OD_ENTRY_H4000 &OD->list[114]
#define OD_ENTRY_H4001 &OD->list[115]
#define OD_ENTRY_H4002 &OD->list[116]
#define OD_ENTRY_H5000 &OD->list[117]
#define OD_ENTRY_H5FFF &OD->list[118]
#define OD_ENTRY_H6040 &OD->list[119]
#define OD_ENTRY_H6041 &OD->list[120]
#define OD_ENTRY_H6060 &OD->list[121]
#define OD_ENTRY_H6061 &OD->list[122]
#define OD_ENTRY_H6062 &OD->list[123]
#define OD_ENTRY_H6064 &OD->list[124]
#define OD_ENTRY_H606B &OD->list[125]
#define OD_ENTRY_H606C &OD->list[126]
#define OD_ENTRY_H607A &OD->list[127]
#define OD_ENTRY_H607C &OD->list[128]
#define OD_ENTRY_H6081 &OD->list[129]
#define OD_ENTRY_H6082 &OD->list[130]
#define OD_ENTRY_H6083 &OD->list[131]
#define OD_ENTRY_H6084 &OD->list[132]
#define OD_ENTRY_H6085 &OD->list[133]
#define OD_ENTRY_H6093 &OD->list[134]
#define OD_ENTRY_H6098 &OD->list[135]
#define OD_ENTRY_H6099 &OD->list[136]
#define OD_ENTRY_H609A &OD->list[137]
#define OD_ENTRY_H60F4 &OD->list[138]
#define OD_ENTRY_H60FD &OD->list[139]
#define OD_ENTRY_H60FE &OD->list[140]
#define OD_ENTRY_H60FF &OD->list[141]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1005_COB_ID_SYNC &OD->list[3]
#define OD_ENTRY_H1006_cyclePeriod &OD->list[4]
#define OD_ENTRY_H1007_syncWindowsLength &OD->list[5]
#define OD_ENTRY_H1008_deviceName &OD->list[6]
#define OD_ENTRY_H1009_hardwareVersion &OD->list[7]
#define OD_ENTRY_H100A_softwareVersion &OD->list[8]
#define OD_ENTRY_H100C_guardTime &OD->list[9]
#define OD_ENTRY_H100D_lifeTimeFactor &OD->list[10]
#define OD_ENTRY_H1010_storeParameters &OD->list[11]
#define OD_ENTRY_H1011_restoreDefaultParameters &OD->list[12]
#define OD_ENTRY_H1014_COB_ID_EmergencyMessage &OD->list[13]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[14]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[15]
#define OD_ENTRY_H1018_identityObject &OD->list[16]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[17]
#define OD_ENTRY_H1600_RPDO_1_mappingParameter &OD->list[18]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[19]
#define OD_ENTRY_H1602_RPDO_3_mappingParameter &OD->list[20]
#define OD_ENTRY_H1603_RPDO_4_mappingParameter &OD->list[21]
#define OD_ENTRY_H1604_RPDO_5_mappingParameter &OD->list[22]
#define OD_ENTRY_H1605_RPDO_6_mappingParameter &OD->list[23]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[24]
#define OD_ENTRY_H1A00_TPDO_1_mappingParameter &OD->list[25]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[26]
#define OD_ENTRY_H1A02_TPDO_3_mappingParameter &OD->list[27]
#define OD_ENTRY_H1A03_TPDO_4_mappingParameter &OD->list[28]
#define OD_ENTRY_H1A04_TPDO_5_mappingParameter &OD->list[29]
#define OD_ENTRY_H1A05_TPDO_6_mappingParameter &OD->list[30]
#define OD_ENTRY_H2000_currentPeak &OD->list[31]
#define OD_ENTRY_H2001_motorResolution &OD->list[32]
#define OD_ENTRY_H2002_standbyTime &OD->list[33]
#define OD_ENTRY_H2003_standbyCurrentPercentage &OD->list[34]
#define OD_ENTRY_H2005_outputs_function &OD->list[35]
#define OD_ENTRY_H2006_enableValidLevel &OD->list[36]
#define OD_ENTRY_H2007_disableMode &OD->list[37]
#define OD_ENTRY_H2008_output1_set &OD->list[38]
#define OD_ENTRY_H2009_filterEnable &OD->list[39]
#define OD_ENTRY_H2010_filterTime &OD->list[40]
#define OD_ENTRY_H2012_softStartTime &OD->list[41]
#define OD_ENTRY_H2013_autotuneEnable &OD->list[42]
#define OD_ENTRY_H2015_currentLoopKp &OD->list[43]
#define OD_ENTRY_H2016_currentLoopKi &OD->list[44]
#define OD_ENTRY_H2017_currentLoopKc &OD->list[45]
#define OD_ENTRY_H2020_motorResistance &OD->list[46]
#define OD_ENTRY_H2021_motorInductance &OD->list[47]
#define OD_ENTRY_H2022_stepTestCurrent &OD->list[48]
#define OD_ENTRY_H2023_stepTestStartStop &OD->list[49]
#define OD_ENTRY_H2024_closeLoopSwitch &OD->list[50]
#define OD_ENTRY_H2026_openCurrentPercentage &OD->list[51]
#define OD_ENTRY_H2027_closeCurrentPercentage &OD->list[52]
#define OD_ENTRY_H2028_antiDisturbanceTime &OD->list[53]
#define OD_ENTRY_H2030_positionErrorAlarmRange &OD->list[54]
#define OD_ENTRY_H2031_positionErrorAlarmEnable &OD->list[55]
#define OD_ENTRY_H2032_dataAcquisitionStartStop &OD->list[56]
#define OD_ENTRY_H2033_dataSampleTime &OD->list[57]
#define OD_ENTRY_H2034_sampleTypeOfChannel_1 &OD->list[58]
#define OD_ENTRY_H2035_positionLoopKp &OD->list[59]
#define OD_ENTRY_H2036_positionLoopKi &OD->list[60]
#define OD_ENTRY_H2037_positionLoopKd &OD->list[61]
#define OD_ENTRY_H2038_positionLoopKvff &OD->list[62]
#define OD_ENTRY_H2039_sumOfPluseInputH &OD->list[63]
#define OD_ENTRY_H2040_sumOfPluseInputL &OD->list[64]
#define OD_ENTRY_H2041_sumOfPluseFeedbackH &OD->list[65]
#define OD_ENTRY_H2042_sumOfPluseFeedbackL &OD->list[66]
#define OD_ENTRY_H2043_speedReference &OD->list[67]
#define OD_ENTRY_H2044_speedFeedback &OD->list[68]
#define OD_ENTRY_H2046_advanceAngle &OD->list[69]
#define OD_ENTRY_H2047_actualSetCurrent &OD->list[70]
#define OD_ENTRY_H2048_busVoltage &OD->list[71]
#define OD_ENTRY_H2049_pulseMode &OD->list[72]
#define OD_ENTRY_H2050_pulseEdgeLevel &OD->list[73]
#define OD_ENTRY_H2051_motorRunningDirection &OD->list[74]
#define OD_ENTRY_H2052_sampleDataType &OD->list[75]
#define OD_ENTRY_H2053_outputModeOfTargetReached &OD->list[76]
#define OD_ENTRY_H2054_antiVibrationCoefficient &OD->list[77]
#define OD_ENTRY_H2056_faultDetectSet &OD->list[78]
#define OD_ENTRY_H2057_clearFaultEnable &OD->list[79]
#define OD_ENTRY_H2058_softStartTime &OD->list[80]
#define OD_ENTRY_H2059_reserve &OD->list[81]
#define OD_ENTRY_H2060_amplitudeOfFirstAntiVibration &OD->list[82]
#define OD_ENTRY_H2061_phaseAOfFirstAntiVibration &OD->list[83]
#define OD_ENTRY_H2062_phaseBOfFirstAntiVibration &OD->list[84]
#define OD_ENTRY_H2063_amplitudeOfSecondAntiVibration &OD->list[85]
#define OD_ENTRY_H2064_phaseAOfSecondAntiVibration &OD->list[86]
#define OD_ENTRY_H2065_phaseBOfSecondAntiVibration &OD->list[87]
#define OD_ENTRY_H2066_amplitudeOfThirdAntiVibration &OD->list[88]
#define OD_ENTRY_H2067_phaseAOfThirdAntiVibration &OD->list[89]
#define OD_ENTRY_H2068_phaseBOfThirdAntiVibration &OD->list[90]
#define OD_ENTRY_H2069_amplitudeOfFourthAntiVibration &OD->list[91]
#define OD_ENTRY_H2070_phaseAOfFourthAntiVibration &OD->list[92]
#define OD_ENTRY_H2071_phaseBOfFourthAntiVibration &OD->list[93]
#define OD_ENTRY_H2072_phaseOfZShaftAntiVibration &OD->list[94]
#define OD_ENTRY_H2073_motorReturnPowerOn &OD->list[95]
#define OD_ENTRY_H2074_torqueFeedforward &OD->list[96]
#define OD_ENTRY_H2075_gravity_compensation &OD->list[97]
#define OD_ENTRY_H2076_pulseTargetReached &OD->list[98]
#define OD_ENTRY_H2093_clearFaultRecord &OD->list[99]
#define OD_ENTRY_H2094_sampleTypeOfChannel_2 &OD->list[100]
#define OD_ENTRY_H2095_sampleTypeOfChannel_3 &OD->list[101]
#define OD_ENTRY_H2096_sampleTypeOfChannel_4 &OD->list[102]
#define OD_ENTRY_H2097_sampleTypeOfChannel_5 &OD->list[103]
#define OD_ENTRY_H2098_sampleTypeOfChannel_6 &OD->list[104]
#define OD_ENTRY_H2099_channelSelection &OD->list[105]
#define OD_ENTRY_H2150_node_ID &OD->list[106]
#define OD_ENTRY_H2151_node_BaudRate &OD->list[107]
#define OD_ENTRY_H2152_inputIoFunctionSet &OD->list[108]
#define OD_ENTRY_H2153_inputIoFilterTime &OD->list[109]
#define OD_ENTRY_H2154_inputIoPolarity &OD->list[110]
#define OD_ENTRY_H2155_inputIoLevel &OD->list[111]
#define OD_ENTRY_H2162_trans_loworhigh &OD->list[112]
#define OD_ENTRY_H3FFE_errorTable &OD->list[113]
#define OD_ENTRY_H4000_motor_code &OD->list[114]
#define OD_ENTRY_H4001_stall_detect_enable &OD->list[115]
#define OD_ENTRY_H4002_stall_proess_set &OD->list[116]
#define OD_ENTRY_H5000_motionFlag &OD->list[117]
#define OD_ENTRY_H5FFF_simulateDriveFaultState &OD->list[118]
#define OD_ENTRY_H6040_controlword &OD->list[119]
#define OD_ENTRY_H6041_statusword &OD->list[120]
#define OD_ENTRY_H6060_modesOfOperation &OD->list[121]
#define OD_ENTRY_H6061_modesOfOperationDisplay &OD->list[122]
#define OD_ENTRY_H6062_commanded_position &OD->list[123]
#define OD_ENTRY_H6064_positionActualValue &OD->list[124]
#define OD_ENTRY_H606B_velocityDemandValue &OD->list[125]
#define OD_ENTRY_H606C_velocityActualValue &OD->list[126]
#define OD_ENTRY_H607A_targetPosition &OD->list[127]
#define OD_ENTRY_H607C_homeOffset &OD->list[128]
#define OD_ENTRY_H6081_profileVelocity &OD->list[129]
#define OD_ENTRY_H6082_end_velocity &OD->list[130]
#define OD_ENTRY_H6083_profileAcceleration &OD->list[131]
#define OD_ENTRY_H6084_profileDeceleration &OD->list[132]
#define OD_ENTRY_H6085_quick_stop_deceleration &OD->list[133]
#define OD_ENTRY_H6093_position_factor &OD->list[134]
#define OD_ENTRY_H6098_hmHomingMethode &OD->list[135]
#define OD_ENTRY_H6099_hmHomingSpeeds &OD->list[136]
#define OD_ENTRY_H609A_hm_homing_acceleration &OD->list[137]
#define OD_ENTRY_H60F4_following_error &OD->list[138]
#define OD_ENTRY_H60FD_digital_inputs &OD->list[139]
#define OD_ENTRY_H60FE_digital_output &OD->list[140]
#define OD_ENTRY_H60FF_targetVelocity &OD->list[141]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = NULL;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = OD_CNT_TIME;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = NULL;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = NULL;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = OD_CNT_GFC;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = OD_CNT_SRDO;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
